name = "ecourts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-07-01"
pages_build_output_dir = "./vercel/output/static"



[[d1_databases]]
binding = "DB"
database_name = "courts"
database_id = "f6a3f887-0ee6-487d-a4c9-9ae6cd40f645"


